name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src
        run: dotnet build -c Release --no-restore

      - name: Test
        working-directory: src
        run: dotnet test -c Release --no-build --verbosity normal